#!/usr/bin/env python3
"""Generate a fixed-cell 1bpp C font header from a TTF using PIL.

Usage: gen_font.py [--ttf PATH] [--size PX] [--out font.h] [--name hacku_font]
Covers printable ASCII (32..126). Cell width = max glyph advance,
cell height = ascent + descent. Emits hacku_font_t (see gfx.h).
"""
import argparse
import os
import sys
from PIL import Image, ImageDraw, ImageFont

FIRST, LAST = 32, 126


def find_default_font():
    """Cross-platform default monospace-bold TTF (Windows/Linux/macOS)."""
    env = os.environ.get("HACKU_TTF")
    if env and os.path.isfile(env):
        return env
    cands = []
    if os.name == "nt":
        windir = os.environ.get("SystemRoot", r"C:\Windows")
        cands += [
            os.path.join(windir, "Fonts", "DejaVuSansMono-Bold.ttf"),
            os.path.join(windir, "Fonts", "consola.ttf"),   # Consolas
            os.path.join(windir, "Fonts", "courbd.ttf"),    # Courier New Bold
            os.path.join(windir, "Fonts", "lucon.ttf"),     # Lucida Console
        ]
    else:
        cands += [
            "/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf",
            "/usr/share/fonts/TTF/DejaVuSansMono-Bold.ttf",
        ]
    # macOS (also useful under Git Bash / MSYS on Windows)
    cands += [
        "/Library/Fonts/DejaVuSansMono-Bold.ttf",
        "/System/Library/Fonts/Menlo.ttc",
        "/System/Library/Fonts/Courier.dfont",
    ]
    for c in cands:
        if c and os.path.isfile(c):
            return c
    return cands[0] if cands else ""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ttf", default=None,
                    help="source TTF (default: auto-detected monospace bold; "
                         "override with HACKU_TTF env)")
    ap.add_argument("--size", type=int, default=18)
    ap.add_argument("--out", default="font.h")
    ap.add_argument("--name", default="hacku_font")
    a = ap.parse_args()

    ttf = a.ttf or find_default_font()
    if not ttf or not os.path.isfile(ttf):
        sys.exit(f"TTF not found: {ttf!r}\n"
                 f"Windows: pass --ttf %SystemRoot%\\Fonts\\consola.ttf\n"
                 f"Debian:  sudo apt install fonts-dejavu-core, then use\n"
                 f"         /usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf\n"
                 f"Or set HACKU_TTF env / pass --ttf PATH.")
    out_dir = os.path.dirname(os.path.abspath(a.out))
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
    try:
        font = ImageFont.truetype(ttf, a.size)
    except Exception as e:
        sys.exit(f"cannot load font {ttf!r}: {e}")
    ascent, descent = font.getmetrics()
    chars = [chr(c) for c in range(FIRST, LAST + 1)]

    probe = Image.new("L", (512, 128), 0)
    d = ImageDraw.Draw(probe)
    max_adv = 0
    for ch in chars:
        max_adv = max(max_adv, int(d.textlength(ch, font=font) + 0.999))
    cw, chh = max_adv, ascent + descent
    stride = (cw + 7) // 8

    glyphs = []
    for ch in chars:
        img = Image.new("L", (cw, chh), 0)
        dd = ImageDraw.Draw(img)
        dd.text((0, 0), ch, font=font, fill=255, anchor="la")
        bits = bytearray(chh * stride)
        px = img.load()
        for yy in range(chh):
            for xx in range(cw):
                if px[xx, yy] >= 128:
                    bits[yy * stride + xx // 8] |= 1 << (7 - (xx & 7))
        glyphs.append(bits)

    with open(a.out, "w", newline="\n", encoding="utf-8") as f:
        f.write("#pragma once\n\n")
        f.write("/* Auto-generated by tools/gen_font.py — do not hand-edit. */\n")
        f.write('#include <stdint.h>\n#include "gfx.h"\n\n')
        f.write(f"static const uint8_t {a.name}_data[] = {{\n")
        for gi, bits in enumerate(glyphs):
            f.write("    /* '%s' (%d) */ " % (chr(FIRST + gi).replace("\\", "\\\\").replace("'", "\\'"),
                                              FIRST + gi))
            f.write(", ".join("0x%02X" % b for b in bits))
            f.write(",\n")
        f.write("};\n\n")
        f.write(f"static const hacku_font_t {a.name} = {{{cw}, {chh}, {FIRST}, "
                f"{LAST - FIRST + 1}, {a.name}_data}};\n")
    print(f"font {cw}x{chh}, {len(chars)} glyphs -> {a.out}")


if __name__ == "__main__":
    main()
